### ISSUE TITLE
Correr php con el server local.

### ISSUE THREAD

**Issue by ssheduardo** [joseluisq/alpine-php-fpm#11]
Vi tú ejemplo de como correr con el servidor local en una solo línea pero me decidí a pasarlo a un docker-compose.yml y hacer pruebas (si vi que tienes una opción de usarlo con nginx) pero como quiero hacer algo simple, bueno al lío.
Tengo este docker-compose.yml

```
version: '3.3'
services:
    php-fpm:
        ports:
            - '8088:80'
        image: 'joseluisq/php-fpm:8.0'
        container_name: php-fpm
        working_dir: /var/www/html
        restart: unless-stopped
        volumes:
            - .:/var/www/html
```
 Veo en los logs que esta bien, pero al ejecutar para lanzar el server local y acceder por el puerto 8088 me da error

Pero al ejecutar

`dce php-fpm php -S 8088:80 -t`

![image](https://user-images.githubusercontent.com/1160138/196699821-e3cbbe56-a950-4c64-99b7-9f0777e8f218.png)

![image](https://user-images.githubusercontent.com/1160138/196700010-3934bd50-a278-42df-8e21-522a3b0f26ec.png)

Qué estoy haciendo mal?

**Comment by joseluisq** [comment]
Tienes un error en tu comando PHP. Debe ser `php -S 127.0.0.1:80 -t`

El asunto es que cuanto quieres ejecutar tu container usandor el comando en una línea, si te das cuenta estás a la vez invocando al servidor de desarrollo de PHP (`php -S 127.0.0.1:80 -t`) por eso debe funcionar.

Pero en tu docker compose al contrario no invocas ningún comando. Prueba agregar un comando al servicio php-fpm de tu archivo docker compose. `command: php -S 127.0.0.1:80 -t`

**Comment by joseluisq** [comment]
Si quieres acceder al container via el navegador por ejemplo tienes que usar un IP que tambien sea accesible.
Por ejemplo ver el siguiente ejemplo:

```yml
version: '3'
services:
  php-fpm:
    ports:
        - '8088:80'
    image: 'joseluisq/php-fpm:8.0'
    command: php -S 0.0.0.0:80 -t .
    container_name: php-fpm
    working_dir: /var/www/html
    volumes:
        - .:/var/www/html
```
