### ISSUE TITLE
How do I CHMOD a dir for a PHP application's caching folder (while using Nginx-alpine example)?

### ISSUE THREAD

**Issue by jnolan7599** [joseluisq/alpine-php-fpm#20]
Hello,

I'm using your docker compose file for nginx as found in the examples dir. The PHP is being served as expected but the web application I'm attempt to get online, [RSS-Bridge](https://github.com/RSS-Bridge/rss-bridge), requires I ensure the cache dir(s) are writable.

```
# Give the http user write permission to the cache folder
chown www-data:www-data /var/www/rss-bridge/cache
```

I've chown'd to _nginx:nginx_, accordingly for both _cache_ & _caches_. The PHP is mounted & served as expected from `/usr/share/nginx/html/rss-bridge`.  Attempting to use it, however, returns:

```
Application Error
The application could not run because of the following error:

Details
Type: Exception
Code: 0
Message: The cache folder is not writeable
File: caches/FileCache.php
Line: 11
Trace
#0 index.php(7): RssBridge->main()
#1 lib/RssBridge.php(15): RssBridge->run()
#2 lib/RssBridge.php(88): DisplayAction->execute()
#3 actions/DisplayAction.php(96): CacheFactory->create()
#4 lib/CacheFactory.php(48): FileCache->__construct()
#5 caches/FileCache.php(11)

Context
Query: action=display&bridge=RedditBridge&context=single&r=selfhosted&f=&score=&d=hot&search=&format=Html
Version: dev.2022-06-14 (git.master.5d8ed2d)
OS: Linux
PHP: 8.2.0
```

While they do offer a Docker image, my host is i386, which they do not have. However my Docker skills are near zero.

What am I doing wrong?

**Comment by joseluisq** [comment]
Basically, it should be enough to `chown` your cache directory only using the proper user and group `www-data` which is the default for this PHP-FPM Docker image. Doing so, it should give write permissions to your `cache` dir.

However, you have two options on how to do it so.

**1. At build time (recommended):** Extending this Docker image, copying your file(s)/dir(s), and changing the owner to get write access for the dir(s) as indicated above like so: 

```Dockerfile
FROM joseluisq/php-fpm:8.2

COPY some/files/. /usr/share/nginx/html/

RUN chown www-data:www-data -R /usr/share/nginx/html/SOME-DIR
```

**2. Or at startup time:** via the docker compose `command` option, changing the owner to get write access for the dir(s) option like so:
```yml
version: "3.3"

services:
    # nginx .....

    php-fpm:
      image: joseluisq/php-fpm
      # CHANGE this at your convenience or use your own entrypoint script
      command: sh -c 'chown www-data:www-data -R /usr/share/nginx/html/SOME-DIR && php-fpm'
      environment:
        - "ENV_SUBSTITUTION_ENABLE=true"
        - "PHP_MEMORY_LIMIT=512M"
        - "PHP_FPM_LISTEN=9090"
        - "PHP_SESSION_GC_MAXLIFETIME=7200"
      expose:
        - "9090"
      volumes:
        - ../public:/usr/share/nginx/html/
```

Remember that the second option will always `chown` your dir(s) every time that the container starts.
